name: "Test and Publish"

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        run: cargo test --all-features

  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    needs:
      - test
    if: startsWith(github.ref, 'refs/tags/')
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest --no-exec --github-repo ${{ github.repository }}

      - name: Display changelog
        run: echo "${{ steps.git-cliff.outputs.content }}"

  publish:
    name: Publish to crates.io
    needs:
      - test
      - generate-changelog
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment: crates.io
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-release
        run: cargo install cargo-release@0.25.19

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo release publish --execute --no-confirm

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          body: ${{ needs.generate-changelog.outputs.release_body }}

