name: "Test and Publish"

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        run: cargo test --all-features

  publish:
    name: Publish to crates.io
    needs:
      - test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment: crates.io
    permissions:
      id-token: write # for OIDC
      contents: write # for releases
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest --no-exec --github-repo ${{ github.repository }}

      - name: Display changelog
        run: echo "${{ steps.git-cliff.outputs.content }}"

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      # TODO: find a way to speed this up
      - name: Install cargo-release
        run: cargo install cargo-release@0.25.19

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo release publish --execute --no-confirm

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          body: ${{ steps.git-cliff.outputs.content }}
